[theme]
primaryColor = "#17191c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f2f3"
textColor = "#17191c"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
